name: 'fhir_pipeline'
version: '1.0.0'
config-version: 2

profile: 'default' 

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fhir_pipeline:
    fhir_clean:  # Bronze layer
      +schema: fhir_clean
      +materialized: table

    silver:      # Silver layer
      +schema: silver
      +materialized: table
